CREATE TABLE [dbo].[SalesLT_SalesOrderHeader] (

	[SalesOrderID] int NULL, 
	[RevisionNumber] smallint NULL, 
	[OrderDate] datetime2(6) NULL, 
	[DueDate] datetime2(6) NULL, 
	[ShipDate] datetime2(6) NULL, 
	[Status] smallint NULL, 
	[TotalDue] decimal(38,18) NULL, 
	[Comment] varchar(8000) NULL, 
	[rowguid] varchar(8000) NULL, 
	[ModifiedDate] datetime2(6) NULL, 
	[BillToAddressID] int NULL, 
	[ShipMethod] varchar(8000) NULL, 
	[CreditCardApprovalCode] varchar(8000) NULL, 
	[SubTotal] decimal(38,18) NULL, 
	[TaxAmt] decimal(38,18) NULL, 
	[Freight] decimal(38,18) NULL, 
	[OnlineOrderFlag] bit NULL, 
	[SalesOrderNumber] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[AccountNumber] varchar(8000) NULL, 
	[CustomerID] int NULL, 
	[ShipToAddressID] int NULL
);